apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: system
  labels:
    control-plane: aws-iam-operator-manager
spec:
  selector:
    matchLabels:
      control-plane: aws-iam-operator-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: aws-iam-operator-manager
    spec:
      containers:
      - args:
        - --enable-leader-election
        image: redradrat/aws-iam-operator:latest
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
